name: Deploy
on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Publish latest image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: gieseladev/wamplius
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - if: contains(github.ref, 'refs/tags/v')
        name: Publish tagged image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: gieseladev/wamplius
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: "true"